# Generated by Django 3.1.4 on 2020-12-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments_on_listing',
            new_name='Comment_on_listing',
        ),
    ]
