# Generated by Django 3.1.4 on 2020-12-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201209_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_on_listing',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
