# Generated by Django 3.1.4 on 2020-12-13 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 22, 8, 29, 384976)),
        ),
    ]
