# Generated by Django 3.1.3 on 2020-12-15 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 21, 47, 17, 124661)),
        ),
    ]
