# Generated by Django 3.1.4 on 2020-12-16 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201215_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 16, 10, 6, 226938)),
        ),
    ]
