# Generated by Django 3.1.4 on 2020-12-17 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201216_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 14, 2, 56, 560686)),
        ),
    ]
