# Generated by Django 3.1.3 on 2020-12-18 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201217_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 7, 14, 21, 141676)),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.Listing'),
        ),
    ]
